In [7]:
import torch
import numpy as np

In [2]:
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [3]:
torch.tensor([1,2,3,4]).dtype

torch.int64

In [4]:
torch.tensor([1,2,3,4], dtype=torch.float32)

tensor([1., 2., 3., 4.])

In [5]:
torch.tensor(range(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
torch.tensor(range(10), dtype=torch.float16)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [8]:
torch.tensor(np.array([1,2,3,4]))

tensor([1, 2, 3, 4], dtype=torch.int32)

In [9]:
torch.tensor([1.,2.,3.,4.]).dtype

torch.float32

In [10]:
torch.tensor(np.array([1.,2.,3.,4.])).dtype

torch.float64

In [11]:
torch.randn(3,3).to(torch.int16)

tensor([[ 0,  0, -2],
        [ 0,  0,  0],
        [ 1,  0, -1]], dtype=torch.int16)

In [12]:
torch.randint(0,5, (3,3)).to(torch.float32)

tensor([[2., 2., 0.],
        [3., 0., 1.],
        [2., 4., 0.]])

### 创建Tensor

In [13]:
torch.rand(3,3)

tensor([[0.3085, 0.8517, 0.2527],
        [0.9310, 0.7229, 0.8430],
        [0.3513, 0.2635, 0.0330]])

In [14]:
torch.randn(2,3,4)

tensor([[[ 0.5299, -1.7209,  0.7123,  0.2612],
         [ 0.2278,  0.1703, -1.1869, -0.3853],
         [-0.7147, -1.0901, -1.2255, -1.0276]],

        [[-0.0559,  0.6787, -0.4318, -0.1317],
         [ 1.4925, -0.5031, -0.1724,  0.1817],
         [-0.6764, -1.4174,  0.2022,  1.1303]]])

In [15]:
torch.zeros(2,2,2)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [16]:
torch.ones(1,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [17]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [18]:
torch.randint(0,10, (3,3))

tensor([[8, 7, 1],
        [9, 6, 0],
        [1, 9, 7]])

In [19]:
t = torch.randn(3,4)

In [20]:
torch.zeros_like(t)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
torch.ones_like(t)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
torch.randn_like(t)

tensor([[-1.3363, -0.2753, -1.2275,  0.0285],
        [ 0.2190, -0.9383, -1.2391,  0.2450],
        [-0.1102,  1.1905,  0.9408,  0.7852]])

In [23]:
t.dtype

torch.float32

In [24]:
t.new_tensor([1,2,2])

tensor([1., 2., 2.])

In [26]:
t.new_empty(1,2)

tensor([[1.0653e-38, 4.2246e-39]])

In [30]:
t.new_full(fill_value=3,size=(2,3))

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [31]:
t.new_ones(1,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.]])

### 存储位置

In [32]:
torch.randn(3,3, device="cpu")

tensor([[-2.0899,  0.5384, -0.3834],
        [-0.5706,  0.0804,  0.0353],
        [ 1.5311,  0.5925,  0.3286]])

In [34]:
torch.randn(3,3, device="cpu").device

device(type='cpu')

In [37]:
torch.cuda.is_available()

False

In [38]:
# 获取在gpu0上面的tensor，转移到gpu1上，再转移到cpu上，再转移到gpu1上
# torch.randn(3,3, device="cuda:0").to("cuda:1").cpu().cuda(1)

### 维度

In [39]:
t = torch.randn(3,4,5)

In [41]:
t.ndim

3

In [42]:
t.ndimension()

3

In [43]:
t.nelement()

60

In [44]:
t.size()

torch.Size([3, 4, 5])

In [45]:
t.shape

torch.Size([3, 4, 5])

In [46]:
t.size(0)

3

In [60]:
t = torch.randn(3,4)

In [61]:
t.view(4,3)

tensor([[ 2.1018,  0.1819, -0.5815],
        [-1.3960,  1.1457,  1.7289],
        [-0.9213, -1.7655,  0.0981],
        [-0.2458,  0.9089,  1.3329]])

In [62]:
t

tensor([[ 2.1018,  0.1819, -0.5815, -1.3960],
        [ 1.1457,  1.7289, -0.9213, -1.7655],
        [ 0.0981, -0.2458,  0.9089,  1.3329]])

In [63]:
t.data_ptr()

2027085993600

In [64]:
t.view(4,3).data_ptr()

2027085993600

In [65]:
t.transpose(0,1)

tensor([[ 2.1018,  1.1457,  0.0981],
        [ 0.1819,  1.7289, -0.2458],
        [-0.5815, -0.9213,  0.9089],
        [-1.3960, -1.7655,  1.3329]])

In [68]:
t = torch.randn(1,2,3)

In [69]:
t.transpose(1,2).shape

torch.Size([1, 3, 2])

In [70]:
t.data_ptr()

2027086350656

In [71]:
t.view(3,2,1).data_ptr()

2027086350656

In [72]:
t.view(3,2,1).contiguous().data_ptr()

2027086350656

In [73]:
t.transpose(1,2).contiguous().data_ptr()

2027086338112

In [74]:
t = torch.randn(3,4)

In [75]:
t

tensor([[ 0.0028,  1.2449, -0.6921,  0.9195],
        [-1.2603, -1.5345, -0.2748,  0.1404],
        [-0.6087,  0.9600,  0.0240, -0.7852]])

In [76]:
t.reshape(4,3)

tensor([[ 0.0028,  1.2449, -0.6921],
        [ 0.9195, -1.2603, -1.5345],
        [-0.2748,  0.1404, -0.6087],
        [ 0.9600,  0.0240, -0.7852]])

In [77]:
t

tensor([[ 0.0028,  1.2449, -0.6921,  0.9195],
        [-1.2603, -1.5345, -0.2748,  0.1404],
        [-0.6087,  0.9600,  0.0240, -0.7852]])

In [78]:
t.view(4,3)

tensor([[ 0.0028,  1.2449, -0.6921],
        [ 0.9195, -1.2603, -1.5345],
        [-0.2748,  0.1404, -0.6087],
        [ 0.9600,  0.0240, -0.7852]])

In [80]:
t.transpose(0,1)

tensor([[ 0.0028, -1.2603, -0.6087],
        [ 1.2449, -1.5345,  0.9600],
        [-0.6921, -0.2748,  0.0240],
        [ 0.9195,  0.1404, -0.7852]])

In [81]:
t.view(1,1,3,4)

tensor([[[[ 0.0028,  1.2449, -0.6921,  0.9195],
          [-1.2603, -1.5345, -0.2748,  0.1404],
          [-0.6087,  0.9600,  0.0240, -0.7852]]]])

### 极值和排序

In [82]:
t = torch.randn(3,4)

In [83]:
t

tensor([[-1.5199,  0.3869, -0.7682,  1.7626],
        [-0.7702,  0.8939,  1.5519,  0.9935],
        [ 0.2368,  0.4724,  1.1237, -0.9528]])

In [84]:
torch.argmax(t, 0)

tensor([2, 1, 1, 0])

In [85]:
torch.argmax(t, 1)

tensor([3, 2, 2])

In [86]:
torch.max(t, 1)

torch.return_types.max(
values=tensor([1.7626, 1.5519, 1.1237]),
indices=tensor([3, 2, 2]))

In [87]:
torch.sort(t, 0)

torch.return_types.sort(
values=tensor([[-1.5199,  0.3869, -0.7682, -0.9528],
        [-0.7702,  0.4724,  1.1237,  0.9935],
        [ 0.2368,  0.8939,  1.5519,  1.7626]]),
indices=tensor([[0, 0, 0, 2],
        [1, 2, 2, 1],
        [2, 1, 1, 0]]))

### 乘法

In [88]:
a = torch.randn(3,4)
b = torch.randn(4,4)

In [89]:
torch.mm(a, b)

tensor([[ 1.0501,  1.5641, -2.6793,  1.5773],
        [ 3.1999,  0.1487,  1.6763, -0.9918],
        [-1.1053,  1.2629, -2.0452,  0.9746]])

In [90]:
a.mm(b)

tensor([[ 1.0501,  1.5641, -2.6793,  1.5773],
        [ 3.1999,  0.1487,  1.6763, -0.9918],
        [-1.1053,  1.2629, -2.0452,  0.9746]])

In [91]:
a = torch.randn(2,3,4)
b = torch.randn(2,4,3)

In [92]:
a.bmm(b)

tensor([[[-0.6277, -1.1672, -2.5727],
         [-2.2468,  0.3890, -0.6197],
         [ 2.7499, -2.8565, -1.0535]],

        [[ 0.2665, -2.2412, -0.3084],
         [-0.3166, -0.6235, -0.4589],
         [ 1.3362, -0.3263, -0.8229]]])

In [93]:
a@b

tensor([[[-0.6277, -1.1672, -2.5727],
         [-2.2468,  0.3890, -0.6197],
         [ 2.7499, -2.8565, -1.0535]],

        [[ 0.2665, -2.2412, -0.3084],
         [-0.3166, -0.6235, -0.4589],
         [ 1.3362, -0.3263, -0.8229]]])

### 拼接和分割

In [99]:
t1 = torch.randn(3,4)
t2 = torch.randn(3,4)
t3 = torch.randn(3,4)
t4 = torch.randn(3,3)

t1,t2,t3,t4

(tensor([[ 0.7001, -0.6315, -0.4288,  0.2750],
         [ 1.8299,  1.0479, -0.5071, -0.3226],
         [ 0.3497,  0.1910,  0.2140,  0.8107]]),
 tensor([[-2.0882,  2.4084, -1.1954,  0.8950],
         [ 0.6763, -1.3862,  0.7106,  0.1877],
         [-0.1359, -0.3602,  0.3628,  0.4087]]),
 tensor([[ 2.0506, -1.3421,  1.0903,  0.1578],
         [-1.9725,  0.3191, -0.0748,  1.5114],
         [ 0.5866, -0.1320, -0.6615,  0.1279]]),
 tensor([[ 0.3596, -0.6702,  0.2830],
         [-1.5989, -0.2411,  1.3739],
         [-1.9172,  0.2543, -1.3786]]))

In [101]:
torch.stack([t1,t2,t3])

tensor([[[ 0.7001, -0.6315, -0.4288,  0.2750],
         [ 1.8299,  1.0479, -0.5071, -0.3226],
         [ 0.3497,  0.1910,  0.2140,  0.8107]],

        [[-2.0882,  2.4084, -1.1954,  0.8950],
         [ 0.6763, -1.3862,  0.7106,  0.1877],
         [-0.1359, -0.3602,  0.3628,  0.4087]],

        [[ 2.0506, -1.3421,  1.0903,  0.1578],
         [-1.9725,  0.3191, -0.0748,  1.5114],
         [ 0.5866, -0.1320, -0.6615,  0.1279]]])

In [102]:
torch.stack([t1,t2,t3], -1)

tensor([[[ 0.7001, -2.0882,  2.0506],
         [-0.6315,  2.4084, -1.3421],
         [-0.4288, -1.1954,  1.0903],
         [ 0.2750,  0.8950,  0.1578]],

        [[ 1.8299,  0.6763, -1.9725],
         [ 1.0479, -1.3862,  0.3191],
         [-0.5071,  0.7106, -0.0748],
         [-0.3226,  0.1877,  1.5114]],

        [[ 0.3497, -0.1359,  0.5866],
         [ 0.1910, -0.3602, -0.1320],
         [ 0.2140,  0.3628, -0.6615],
         [ 0.8107,  0.4087,  0.1279]]])

In [103]:
torch.stack([t1,t2,t3], 1)

tensor([[[ 0.7001, -0.6315, -0.4288,  0.2750],
         [-2.0882,  2.4084, -1.1954,  0.8950],
         [ 2.0506, -1.3421,  1.0903,  0.1578]],

        [[ 1.8299,  1.0479, -0.5071, -0.3226],
         [ 0.6763, -1.3862,  0.7106,  0.1877],
         [-1.9725,  0.3191, -0.0748,  1.5114]],

        [[ 0.3497,  0.1910,  0.2140,  0.8107],
         [-0.1359, -0.3602,  0.3628,  0.4087],
         [ 0.5866, -0.1320, -0.6615,  0.1279]]])

stack 指的是要拼接的原始的子tensor中的维度，将这些子tensor对应维度的值取出来，拼接到新的tensor中

In [104]:
torch.cat([t1,t2,t3])

tensor([[ 0.7001, -0.6315, -0.4288,  0.2750],
        [ 1.8299,  1.0479, -0.5071, -0.3226],
        [ 0.3497,  0.1910,  0.2140,  0.8107],
        [-2.0882,  2.4084, -1.1954,  0.8950],
        [ 0.6763, -1.3862,  0.7106,  0.1877],
        [-0.1359, -0.3602,  0.3628,  0.4087],
        [ 2.0506, -1.3421,  1.0903,  0.1578],
        [-1.9725,  0.3191, -0.0748,  1.5114],
        [ 0.5866, -0.1320, -0.6615,  0.1279]])

In [105]:
torch.cat([t1,t2,t3], dim=1)

tensor([[ 0.7001, -0.6315, -0.4288,  0.2750, -2.0882,  2.4084, -1.1954,  0.8950,
          2.0506, -1.3421,  1.0903,  0.1578],
        [ 1.8299,  1.0479, -0.5071, -0.3226,  0.6763, -1.3862,  0.7106,  0.1877,
         -1.9725,  0.3191, -0.0748,  1.5114],
        [ 0.3497,  0.1910,  0.2140,  0.8107, -0.1359, -0.3602,  0.3628,  0.4087,
          0.5866, -0.1320, -0.6615,  0.1279]])

In [106]:
t1 = torch.randn(3,12)

In [107]:
torch.chunk(t1, 3, -1)

(tensor([[ 0.0666, -2.1999, -1.2847, -1.1800],
         [-3.4401, -1.6972, -1.0236, -0.3353],
         [-0.8535,  1.4430,  0.0141,  1.2620]]),
 tensor([[-1.7920, -0.6809, -0.0189,  2.1369],
         [ 0.0476, -0.8315, -1.3015,  2.4054],
         [-0.0769,  0.4974, -0.5468, -1.1677]]),
 tensor([[-1.1824,  0.7116, -1.1257, -0.5178],
         [ 0.6180,  0.5960,  0.4748, -0.7742],
         [ 1.1620, -0.4613,  0.7109, -1.6746]]))

### 维度变化

In [108]:
t = torch.randn(3,4)

In [112]:
t,t.shape

(tensor([[-0.8433,  0.6941,  0.2301, -0.9674],
         [ 0.1531, -1.3546,  0.0582, -0.0682],
         [-0.3375, -0.1276, -0.7241,  1.9731]]), torch.Size([3, 4]))

In [113]:
t1 = t.unsqueeze(-1)
t1, t1.shape

(tensor([[[-0.8433],
          [ 0.6941],
          [ 0.2301],
          [-0.9674]],
 
         [[ 0.1531],
          [-1.3546],
          [ 0.0582],
          [-0.0682]],
 
         [[-0.3375],
          [-0.1276],
          [-0.7241],
          [ 1.9731]]]), torch.Size([3, 4, 1]))

In [114]:
t1 = t.unsqueeze(0)
t1, t1.shape

(tensor([[[-0.8433,  0.6941,  0.2301, -0.9674],
          [ 0.1531, -1.3546,  0.0582, -0.0682],
          [-0.3375, -0.1276, -0.7241,  1.9731]]]), torch.Size([1, 3, 4]))

In [115]:
t1 = t.unsqueeze(1)
t1, t1.shape

(tensor([[[-0.8433,  0.6941,  0.2301, -0.9674]],
 
         [[ 0.1531, -1.3546,  0.0582, -0.0682]],
 
         [[-0.3375, -0.1276, -0.7241,  1.9731]]]), torch.Size([3, 1, 4]))

In [116]:
t = torch.rand(1,3,4,1)
t, t.shape

(tensor([[[[0.7479],
           [0.2319],
           [0.8628],
           [0.1753]],
 
          [[0.3255],
           [0.3460],
           [0.9846],
           [0.0706]],
 
          [[0.9358],
           [0.2218],
           [0.1403],
           [0.5828]]]]), torch.Size([1, 3, 4, 1]))

In [117]:
t1 = t.squeeze()
t1, t1.shape

(tensor([[0.7479, 0.2319, 0.8628, 0.1753],
         [0.3255, 0.3460, 0.9846, 0.0706],
         [0.9358, 0.2218, 0.1403, 0.5828]]), torch.Size([3, 4]))